name: CI-CD BASE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: script build
        run: echo "This is a build job"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: script build
        run: echo "this is a test job"
 
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: script build
        run: echo "this is a deploy job"

  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: script build
        run: |
          # mostramos las keys
          ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} -i ${{secrets.SSH_PASSWORD}} "ls -la"